apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
{{ include "labels.standard" . | indent 4 }}
data: 
  {{- (.Files.Glob "files/**.yaml").AsConfig | nindent 2 }}
