apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  labels:
    name: {{ .Values.name }}
{{ include "labels.standard" . | indent 4 }}
type: "kubernetes.io/storageos"
data:
  ELASTICSEARCH_USERNAME: {{ default "" .Values.elasticsearch.username | b64enc | quote }}
  ELASTICSEARCH_PASSWORD: {{ default "" .Values.elasticsearch.password | b64enc | quote }}
  MAILSERVER_USERNAME: {{ default "" .Values.mailserver.username | b64enc | quote }}
  MAILSERVER_PASSWORD: {{ default "" .Values.mailserver.password | b64enc | quote }}
  TELEGRAM_TOKEN: {{ default "" .Values.telegram.token | b64enc | quote }}
