spring:
  application:
    name: elastic-monitor
  mail:
    host: ${MAIL_SERVER_HOST:mailhost.example}
    port: ${MAIL_SERVER_PORT:25}
    username: ${MAIL_SERVER_USERNAME:}
    password: ${MAIL_SERVER_PASSWORD:}

rules:
  #location: ${RULES_LOCATION:src/main/resources/rules/offers-without-default-price.yaml}
  location: ${RULES_LOCATION:/app/resources/rules}

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}

telegram:
  token: ${TELEGRAM_TOKEN:}