name: Non-retired Offers do not have default price

#Schedule for rule (how often it will be checked). "cron" and "interval" are supported
#At least one value is required!
#cron has higher priority than interval
trigger:
  #cron: "0 * * ? * *"
  interval: 1000              #Interval in seconds

#Query to run against elasticsearch
query:
  index: offer
  value: '{
          		"bool": {
          			"must_not": [
          				{
          					"nested": {
          						"path": "defaultPrice",
          						"query": {
          							"bool": {
          								"filter": {
          									"exists": {
          										"field": "defaultPrice"
          									}
          								}
          							}
          						}
          					}
          				},
          				{
                            "term": {
                                "lifecycleStatus": "RETIRED"
                            }
                        }
          			]
          		}
          }'

#Condition to check "query" against. I.e. "query" results are compared against this condition to check if
#condition was breached
condition:
  field: "/hits/total/value"     #field in query json response to check against
  fieldType: int                 #field type of json field. Supported values: int, boolean, double, float, long, string
  op: eq                         #comparison operation of "field". Supported values: eq, gte, gt, lt, lte
  value: 0                       #value to check "field" against using "op" operator. Will be casted to type
                                     #specified in "fieldType"

transform:
  index: offer
  query: 123

#Actions to execute when condition was breached
#Supported values are: email, telegram, log (set via "type" field)
action:
  - name: Email to PCC
    type: email
    to: test@test.com
    subject: "ERROR: Found offers without default price!"
    body: "Found {{[search:/hits/total/value]}} offers without default price under {{query.index}} index in {{[env:elasticsearch.host]}}"

  - name: Log alert to console
    type: log
    message: "\u2757 \u2757 \u2757 \u2757 \n
                          Found *{{[search:/hits/total/value]}} offers without default price* under {{query.index}} index in {{[env:elasticsearch.host]}} \n
                          \u2757 \u2757 \u2757 \u2757"

  - name: Send message to telegram channel
    type: telegram
    channelId: -452773100
    message: "\u2757 \u2757 \u2757 \u2757 \n
                          Found *{{[search:/hits/total/value]}} offers without default price* under {{query.index}} index in {{[env:elasticsearch.host]}} \n
                          \u2757 \u2757 \u2757 \u2757"
